[project]
name = "taskify-order"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "taskify-common",
]

[tool.uv.sources]
taskify-common = { path = "../taskify-components/taskify-common" }
