[project]
name = "taskify-admin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "taskify_common",
]

[tool.uv.sources]
taskify_common = { path = "../taskify_components/taskify_common" }
