[project]
name = "taskify-order"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "taskify_common",
]

[tool.uv.sources]
taskify_common = { workspace = true }
